# To update version and release
# - Update version in `package.json`
# - Commit change (e.g. `commit -am v1.2.3`)
# - Tag commit (e.g. `git tag v1.2.3`)
# - Push to git (`git push && git push --tags`)

name: Electron Build

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    
    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: NodeJS setup
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Build
      run: |
        npm i
        npm run dist
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}